---
title: 'Your title'
subtitle: 'Conference / Panel name'
author: 'Philipp Kleer'
institute: 'Department of Political Science | Justus-Liebig-University Giessen' 
# User socials
mastodon: 'philk'
mastodonurl: 'https://polsci.social/@'
bluesky: 'phil-k'
#twitterx: '_philk'
git: 'bpkleer'
orcid: '0000-0003-1935-387X'
lattes: '4785970328498860'
researchgate: 'Philipp-Kleer'
contactemail: 'philipp.kleer+academia@posteo.com'
contactsite: 'https://bpkleer.github.io/en'
qrcode: '{{< qrcode https://bpkleer.github.io qr-start colorDark="#5A5A5A" >}}'
# Settings
date: 'Report Last Run: `r Sys.time()`'
date-format: long
bibliography: assets/lit.bib
csl: assets/apa.csl
format:  
  revealjs: 
    width: 1600
    height: 900
    template-partials: 
      - ./assets/title-slide.html
    theme: [default, './assets/slides.scss']
    navigation-mode: vertical
    controls-layout: bottom-right
    controls-tutorial: true
    multiplex: true #Creates speaker and normal html
    touch: true
    menu: false
    preview-links: auto
    transition: slide
    background-transition: fade
    code-fold: false
    code-summary: 'Click here for Code'  
    code-link: true
    code-overflow: wrap
    highlight-style: atom-one 
    footer: '[{{< fa brands github >}}](https://github.com/bpkleer){.github}'
    execute:
      echo: false
      eval: true
      warning: false
      message: false
    chalkboard:
      src: './assets/drawings.json'
      buttons: false
    title-slide-attributes:
      data-state: 'hide-menubar'
    simplemenu:
        barhtml:
            header: '<div class="menubar"><a href="#"></a><ul class="menu"></ul><div>'
        scale: 0.8
revealjs-plugins:
  - simplemenu
editor: source
---

```{r}
#| label: setup-libraries-data
#| include: false

library(tidyverse)
library(knitr)
library(kableExtra)

myhelpers::load_slidecols()
```

# Quarto {data-stack-name="Start"}

Remember this is the first level! 

## In Positron

You need to add extensions manually (`rstudioapi` doesn't work there):

- `quarto install extension sellorm/quarto-social-embeds`
- `quarto install extension schochastics/academicons`
- `quarto add martinomagnifico/quarto-simplemenu`
- `quarto add mcanouil/quarto-iconify`
- `quarto add quarto-ext/fontawesome`
- `quarto install extension jmbuhr/quarto-qrcode`

## Second level slide

This is the content level.

# Goodbye {.goodbye data-state="hide-menubar"}

[Please, shoot questions at me. {{< iconify ph person-simple-throw-fill >}}]{.greetings} [If you use citations, put  before \@ in usernames]{.greetings}

::: qrcode-final
{{< fa regular person-chalkboard size=3x >}} {{< qrcode https://bpkleer.github.io qr-end colorDark="#5A5A5A" >}}
:::

::: social
**Contact:**

[{{< fa brands mastodon >}}](https://polsci.social/@philk){.mastodon} [\@philk](https://polsci.social/@philk) \| [{{< fa solid square >}}](https://bsky.app/profile/phil-k.bsky.social){.bluesky} [\@phil-k](https://bsky.app/profile/phil-k.bsky.social) \| [{{< fa brands github >}}](https://github.com/bpkleer){.github} [bpkleer](https://github.com/bpkleer)

[{{< ai orcid >}}](https://orcid.org/0000-0003-1935-387X){.orcid} [0000-0003-1935-387X](https://orcid.org/0000-0003-1935-387X) \| [{{< ai lattes >}}](http://lattes.cnpq.br/4785970328498860){.lattes} [4785970328498860](http://lattes.cnpq.br/4785970328498860) \| [{{< ai researchgate-square >}}](https://www.researchgate.net/profile/Philipp-Kleer){.researchgate} [Philipp-Kleer](https://www.researchgate.net/profile/Philipp-Kleer)

[{{< fa envelope >}}](mailto:philipp.kleer+academia@posteo.com){.email}[ philipp.kleer+academia@posteo.com](mailto:philipp.kleer+academia@posteo.com) \| [{{< fa globe >}}](https://bpkleer.github.io){.website}[ bpkleer.github.io](https://bpkleer.github.io)
:::

::: footer
:::

## References {visibility="uncounted"}

::: {#refs}
:::
